-- MySQL Script generated by MySQL Workbench
-- Thu Sep 15 12:45:23 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema exometis1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema exometis1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `exometis1` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Communes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Communes` (
  `idCommunes` INT NOT NULL AUTO_INCREMENT,
  `NomCommunes` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`idCommunes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comptables`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comptables` (
  `idComptables` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(70) NOT NULL,
  `Prenom` VARCHAR(70) NOT NULL,
  `Age` INT NOT NULL,
  `Telephone` INT NOT NULL,
  `Agences_idAgences` INT NOT NULL,
  PRIMARY KEY (`idComptables`, `Agences_idAgences`),
  INDEX `fk_Comptables_Agences_idx` (`Agences_idAgences` ASC) VISIBLE,
  CONSTRAINT `fk_Comptables_Agences`
    FOREIGN KEY (`Agences_idAgences`)
    REFERENCES `mydb`.`Agences` (`idAgences`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Agences`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Agences` (
  `idAgences` INT NOT NULL AUTO_INCREMENT,
  `NomAgence` VARCHAR(70) NOT NULL,
  `Communes_idCommunes` INT NOT NULL,
  `Comptables_idComptables` INT NOT NULL,
  PRIMARY KEY (`idAgences`, `Communes_idCommunes`),
  INDEX `fk_Agences_Communes1_idx` (`Communes_idCommunes` ASC) VISIBLE,
  INDEX `fk_Agences_Comptables1_idx` (`Comptables_idComptables` ASC) VISIBLE,
  CONSTRAINT `fk_Agences_Communes1`
    FOREIGN KEY (`Communes_idCommunes`)
    REFERENCES `mydb`.`Communes` (`idCommunes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Agences_Comptables1`
    FOREIGN KEY (`Comptables_idComptables`)
    REFERENCES `mydb`.`Comptables` (`idComptables`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Exploitation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Exploitation` (
  `idExploitation` INT NOT NULL AUTO_INCREMENT,
  `NomExploitation` VARCHAR(70) NOT NULL,
  `SAU` VARCHAR(70) NOT NULL,
  `Comptables_idComptables` INT NOT NULL,
  `Communes_idCommunes` INT NOT NULL,
  PRIMARY KEY (`idExploitation`, `Comptables_idComptables`, `Communes_idCommunes`),
  INDEX `fk_Exploitation_Comptables1_idx` (`Comptables_idComptables` ASC) VISIBLE,
  INDEX `fk_Exploitation_Communes1_idx` (`Communes_idCommunes` ASC) VISIBLE,
  CONSTRAINT `fk_Exploitation_Comptables1`
    FOREIGN KEY (`Comptables_idComptables`)
    REFERENCES `mydb`.`Comptables` (`idComptables`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Exploitation_Communes1`
    FOREIGN KEY (`Communes_idCommunes`)
    REFERENCES `mydb`.`Communes` (`idCommunes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Diriger`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Diriger` (
)
ENGINE = InnoDB;

USE `exometis1` ;

-- -----------------------------------------------------
-- Table `exometis1`.`commandes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exometis1`.`commandes` (
  `numcommande` INT(11) NOT NULL AUTO_INCREMENT,
  `correspondant` VARCHAR(255) NOT NULL,
  `date_commande` DATE NOT NULL,
  `date_livraison` DATE NOT NULL,
  `montant_commande` DECIMAL(10,0) NOT NULL,
  PRIMARY KEY (`numcommande`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `exometis1`.`fournisseurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exometis1`.`fournisseurs` (
  `nom` VARCHAR(70) NOT NULL,
  `adresse` VARCHAR(255) NULL DEFAULT NULL,
  `telephone` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`nom`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `exometis1`.`commandes_passees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exometis1`.`commandes_passees` (
  `commandes_numcommande` INT(11) NOT NULL,
  `fournisseurs_nom` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`commandes_numcommande`, `fournisseurs_nom`),
  INDEX `fk_commandes_has_fournisseurs_fournisseurs1` (`fournisseurs_nom` ASC) VISIBLE,
  CONSTRAINT `fk_commandes_has_fournisseurs_commandes`
    FOREIGN KEY (`commandes_numcommande`)
    REFERENCES `exometis1`.`commandes` (`numcommande`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commandes_has_fournisseurs_fournisseurs1`
    FOREIGN KEY (`fournisseurs_nom`)
    REFERENCES `exometis1`.`fournisseurs` (`nom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `exometis1`.`produits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exometis1`.`produits` (
  `libelle` VARCHAR(255) NOT NULL,
  `prix_vente_unit` DECIMAL(10,0) NOT NULL,
  `stock` INT(11) NOT NULL,
  PRIMARY KEY (`libelle`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `exometis1`.`fournisseurs_produits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exometis1`.`fournisseurs_produits` (
  `fournisseurs_nom` VARCHAR(70) NOT NULL,
  `produits_libelle` VARCHAR(255) NOT NULL,
  `prix_unit` DECIMAL(10,0) NOT NULL,
  PRIMARY KEY (`fournisseurs_nom`, `produits_libelle`),
  INDEX `fk_fournisseurs_has_produits_produits1` (`produits_libelle` ASC) VISIBLE,
  CONSTRAINT `fk_fournisseurs_has_produits_fournisseurs1`
    FOREIGN KEY (`fournisseurs_nom`)
    REFERENCES `exometis1`.`fournisseurs` (`nom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fournisseurs_has_produits_produits1`
    FOREIGN KEY (`produits_libelle`)
    REFERENCES `exometis1`.`produits` (`libelle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `exometis1`.`produits_commandes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exometis1`.`produits_commandes` (
  `produits_libelle` VARCHAR(255) NOT NULL,
  `commandes_numcommande` INT(11) NOT NULL,
  `quantite` INT(11) NOT NULL,
  PRIMARY KEY (`produits_libelle`, `commandes_numcommande`),
  INDEX `fk_produits_has_commandes_commandes1` (`commandes_numcommande` ASC) VISIBLE,
  CONSTRAINT `fk_produits_has_commandes_commandes1`
    FOREIGN KEY (`commandes_numcommande`)
    REFERENCES `exometis1`.`commandes` (`numcommande`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produits_has_commandes_produits1`
    FOREIGN KEY (`produits_libelle`)
    REFERENCES `exometis1`.`produits` (`libelle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
